=begin

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

=end

@pentagonals = [1]
@hexagonals = [1]

def pentagonal?(number)
  if number <= @pentagonals[-1]
    return @pentagonals.include?(number)
  else
    while @pentagonals[-1] < number
      n = @pentagonals.length + 1
      @pentagonals << n * (3 * n - 1) / 2
      if @pentagonals[-1] == number
        return true
      end
    end
    return false
  end
end

def hexagonal?(number)
  if number <= @hexagonals[-1]
    return @hexagonals.include?(number)
  else
    while @hexagonals[-1] < number
      n = @hexagonals.length + 1
      @hexagonals << n * (2 * n - 1)
      if @hexagonals[-1] == number
        return true
      end
    end
    return false
  end
end

i = 285
continue = true
while continue
  i += 1
  t_i = i * ( i + 1 ) / 2
  if pentagonal?(t_i) && hexagonal?(t_i)
    continue = false
  end
end

p t_i  # => 1533776805