=begin

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

=end

start = Time.now

divisors =[]
current_triangle = 0
natural_number = 1
while divisors.length <= 500 do
  current_triangle += natural_number
  natural_number += 1
  divisors = []
  i = 1
  ((Math.sqrt(current_triangle)).to_i).times do
    if current_triangle % i == 0
      divisors << i
      unless current_triangle / i == i
        divisors << (current_triangle / i)
      end
    end
    i += 1
  end
end

p current_triangle  # => 76576500

finish = Time.now
# print the time it took to run the program in seconds
p finish - start # => 5.378025