=begin

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end

fibonacci = [1]
sum = 0
value = 1
while value < 4000000
  fibonacci << value
  value = fibonacci[fibonacci.length - 1] + fibonacci[fibonacci.length - 2]
end

fibonacci.each do |element|
  if element % 2 == 0
    sum += element
  end
end

p sum
