import { fibonacciNumbersUpTo } from '../lib/fibonacci/fibonacciNumbersUpTo'
import { sum } from '../lib/sum/sum'

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

export const sumOfEvenValuedFibs = (ceiling: number): number => {
  let sequence = fibonacciNumbersUpTo(ceiling, [1, 2])
  let evensInSequence = sequence.filter(number => number % 2 === 0)
  return sum(evensInSequence)
}
